import { Users, Truck, Building2, CalendarDays } from "lucide-react";

/* ── Global Stat Cards Data ── */
export const stats = [
    {
        label: "Employees",
        value: "70",
        sub: "Departments 08",
        icon: Users,
        iconBg: "bg-violet-100",
        iconColor: "text-violet-600",
        valueColor: "text-gray-900",
        hasArrow: true,
    },
    {
        label: "Vehicles",
        value: "06",
        sub: "Based on Last 30 days",
        icon: Truck,
        iconBg: "bg-blue-100",
        iconColor: "text-blue-600",
        valueColor: "text-gray-900",
        hasArrow: false,
    },
    {
        label: "Company",
        value: "12",
        sub: "With in 30 days",
        icon: Building2,
        iconBg: "bg-orange-100",
        iconColor: "text-orange-500",
        valueColor: "text-orange-500",
        hasArrow: true,
    },
    {
        label: "Other",
        value: "12",
        sub: "Birthdays , Special Even...",
        icon: CalendarDays,
        iconBg: "bg-violet-100",
        iconColor: "text-violet-600",
        valueColor: "text-violet-600",
        hasArrow: true,
    },
];

/* ── Global Employees Dataset (15 Records) ── */
export const employees = [
    {
        name: "Sundar Pichai",
        id: "EMP-042",
        dept: "Sales",
        title: "Sales Executive",
        date: "12 Oct 2026",
        doc: "Visa",
        days: 5,
        avatar: "https://i.pravatar.cc/80?img=11",
        color: "text-rose-500",
        email: "Sundarpichai@company.com",
        mobile: "+971 50 123 4567",
        department: "Designer",
        joinedDate: "12 Mar 2023",
        manager: "Sarah Jenkins",
        salary: "8,000",
        emiratesId: "784-1988-1234567-1",
        emiratesExp: "Exp: 10/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 10/2027",
    },
    {
        name: "Jane Smith",
        id: "EMP-043",
        dept: "Marketing",
        title: "Marketing Manager",
        date: "15 Oct 2026",
        doc: "Health Insurance",
        days: 4,
        initials: "JS",
        bg: "bg-violet-600",
        color: "text-rose-500",
        email: "Janesmith@company.com",
        mobile: "+971 50 234 5678",
        department: "Marketing",
        joinedDate: "15 Jan 2022",
        manager: "Robert Vance",
        salary: "9,500",
        emiratesId: "784-1991-9876543-2",
        emiratesExp: "Exp: 11/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 11/2027",
    },
    {
        name: "Bob Taylor",
        id: "EMP-044",
        dept: "Development",
        title: "Senior Developer",
        date: "20 Oct 2026",
        doc: "Visa",
        days: 3,
        initials: "BT",
        bg: "bg-emerald-600",
        color: "text-rose-500",
        email: "Bobtaylor@company.com",
        mobile: "+971 50 345 6789",
        department: "Development",
        joinedDate: "01 Jun 2021",
        manager: "Alex Rivera",
        salary: "12,000",
        emiratesId: "784-1985-5554443-3",
        emiratesExp: "Exp: 08/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 08/2027",
    },
    {
        name: "Emily Martinez",
        id: "EMP-045",
        dept: "Design",
        title: "UI/UX Designer",
        date: "25 Oct 2026",
        doc: "Passport",
        days: 6,
        initials: "EM",
        bg: "bg-amber-500",
        color: "text-rose-500",
        email: "Emily.m@company.com",
        mobile: "+971 50 456 7890",
        department: "Design",
        joinedDate: "10 Aug 2023",
        manager: "Sarah Jenkins",
        salary: "8,500",
        emiratesId: "784-1994-1122334-4",
        emiratesExp: "Exp: 12/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 12/2027",
    },
    {
        name: "Rachel Park",
        id: "EMP-046",
        dept: "HR",
        title: "HR Specialist",
        date: "30 Oct 2026",
        doc: "Visa",
        days: 2,
        initials: "RP",
        bg: "bg-rose-500",
        color: "text-rose-500",
        email: "Rachel.p@company.com",
        mobile: "+971 50 567 8901",
        department: "Human Resources",
        joinedDate: "05 Feb 2020",
        manager: "Helen Zhang",
        salary: "7,800",
        emiratesId: "784-1992-6677889-5",
        emiratesExp: "Exp: 05/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 05/2027",
    },
    {
        name: "Michael Wong",
        id: "EMP-047",
        dept: "Finance",
        title: "Financial Analyst",
        date: "05 Nov 2026",
        doc: "Health Insurance",
        days: 7,
        initials: "MW",
        bg: "bg-[#8E8E93]",
        color: "text-rose-500",
        email: "Michael.w@company.com",
        mobile: "+971 50 678 9012",
        department: "Finance",
        joinedDate: "18 Nov 2022",
        manager: "Marcus Cole",
        salary: "10,200",
        emiratesId: "784-1989-3344556-6",
        emiratesExp: "Exp: 09/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 09/2027",
    },
    {
        name: "Kathy Lee",
        id: "EMP-048",
        dept: "Customer Support",
        title: "Support Lead",
        date: "Today",
        doc: "Visa",
        days: 0,
        initials: "KL",
        bg: "bg-indigo-600",
        color: "text-rose-600",
        email: "Kathy.l@company.com",
        mobile: "+971 50 789 0123",
        department: "Customer Support",
        joinedDate: "22 Apr 2023",
        manager: "Sarah Jenkins",
        salary: "8,200",
        emiratesId: "784-1995-7788990-7",
        emiratesExp: "Exp: 04/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 04/2027",
    },
    {
        name: "Alex Diaz",
        id: "EMP-049",
        dept: "Operations",
        title: "Operations Admin",
        date: "15 Nov 2026",
        doc: "Passport",
        days: 1,
        initials: "AD",
        bg: "bg-cyan-600",
        color: "text-rose-500",
        email: "Alex.d@company.com",
        mobile: "+971 50 890 1234",
        department: "Operations",
        joinedDate: "14 Sep 2021",
        manager: "David Miller",
        salary: "9,000",
        emiratesId: "784-1987-2233445-8",
        emiratesExp: "Exp: 07/2027",
        visaType: "Employment visa",
        visaExp: "Exp: 07/2027",
    },
    {
        name: "David Kim",
        id: "EMP-050",
        dept: "Sales",
        title: "Account Executive",
        date: "Yesterday",
        doc: "Visa",
        days: -1,
        initials: "DK",
        bg: "bg-blue-600",
        color: "text-rose-700",
        email: "David.k@company.com",
        mobile: "+971 50 901 2345",
        department: "Sales",
        joinedDate: "03 Mar 2023",
        manager: "Sundar Pichai",
        salary: "8,700",
        emiratesId: "784-1996-8899001-9",
        emiratesExp: "Exp: 03/2028",
        visaType: "Employment visa",
        visaExp: "Exp: 03/2028",
    },
    {
        name: "Sophia Chen",
        id: "EMP-051",
        dept: "Marketing",
        title: "SEO Lead",
        date: "22 Nov 2026",
        doc: "Health Insurance",
        days: 12,
        initials: "SC",
        bg: "bg-fuchsia-600",
        color: "text-amber-500",
        email: "Sophia.c@company.com",
        mobile: "+971 50 012 3456",
        department: "Marketing",
        joinedDate: "11 Oct 2022",
        manager: "Jane Smith",
        salary: "9,100",
        emiratesId: "784-1997-1122334-0",
        emiratesExp: "Exp: 10/2028",
        visaType: "Employment visa",
        visaExp: "Exp: 10/2028",
    },
    {
        name: "Lucas Silva",
        id: "EMP-052",
        dept: "Development",
        title: "Backend Engineer",
        date: "28 Nov 2026",
        doc: "Passport",
        days: 14,
        initials: "LS",
        bg: "bg-emerald-500",
        color: "text-emerald-500",
        email: "Lucas.s@company.com",
        mobile: "+971 50 123 9988",
        department: "Development",
        joinedDate: "19 May 2021",
        manager: "Bob Taylor",
        salary: "11,500",
        emiratesId: "784-1993-4455667-1",
        emiratesExp: "Exp: 05/2028",
        visaType: "Employment visa",
        visaExp: "Exp: 05/2028",
    },
    {
        name: "Olivia White",
        id: "EMP-053",
        dept: "Design",
        title: "Product Designer",
        date: "02 Dec 2026",
        doc: "Visa",
        days: 18,
        initials: "OW",
        bg: "bg-purple-600",
        color: "text-emerald-500",
        email: "Olivia.w@company.com",
        mobile: "+971 50 234 8877",
        department: "Design",
        joinedDate: "07 Dec 2022",
        manager: "Emily Martinez",
        salary: "8,900",
        emiratesId: "784-1998-5566778-2",
        emiratesExp: "Exp: 12/2028",
        visaType: "Employment visa",
        visaExp: "Exp: 12/2028",
    },
];

/* ── Global Vehicles Dataset (10 Records) ── */
export const vehicles = [
    {
        number: "DXB 12345",
        model: "Toyota Camry 2023",
        type: "Sedan",
        subtext: "Sedan • White",
        driver: "Sundar Pichai",
        avatar: "https://i.pravatar.cc/80?img=11",
        insuranceExp: "Today",
        regExp: "15 Nov 2026",
        status: "Expiring Today",
        days: 0,
    },
    {
        number: "DXB 88291",
        model: "Nissan Patrol 2024",
        type: "SUV",
        subtext: "SUV • Black",
        driver: "Jane Smith",
        avatar: "https://i.pravatar.cc/80?img=5",
        insuranceExp: "20 Nov 2026",
        regExp: "18 Dec 2026",
        status: "Valid",
        days: 15,
    },
    {
        number: "DXB 55432",
        model: "Ford F-150 2022",
        type: "Truck",
        subtext: "Truck • Silver",
        driver: "Bob Taylor",
        avatar: "https://i.pravatar.cc/80?img=12",
        insuranceExp: "05 Oct 2026",
        regExp: "10 Oct 2026",
        status: "Expiring Soon",
        days: 5,
    },
    {
        number: "DXB 99012",
        model: "Toyota Land Cruiser",
        type: "SUV",
        subtext: "SUV • White",
        driver: "Michael Wong",
        avatar: "https://i.pravatar.cc/80?img=15",
        insuranceExp: "12 Dec 2026",
        regExp: "15 Jan 2027",
        status: "Valid",
        days: 28,
    },
    {
        number: "DXB 33411",
        model: "Honda Accord 2023",
        type: "Sedan",
        subtext: "Sedan • Blue",
        driver: "Rachel Park",
        avatar: "https://i.pravatar.cc/80?img=9",
        insuranceExp: "01 Nov 2026",
        regExp: "05 Dec 2026",
        status: "Valid",
        days: 6,
    },
    {
        number: "DXB 77654",
        model: "Mercedes Sprinter",
        type: "Truck",
        subtext: "Van • White",
        driver: "Alex Diaz",
        avatar: "https://i.pravatar.cc/80?img=18",
        insuranceExp: "Yesterday",
        regExp: "20 Oct 2026",
        status: "Expired Yesterday",
        days: -1,
    },
    {
        number: "DXB 44109",
        model: "BMW X5 2024",
        type: "SUV",
        subtext: "SUV • Grey",
        driver: "David Kim",
        avatar: "https://i.pravatar.cc/80?img=20",
        insuranceExp: "10 Jan 2027",
        regExp: "14 Feb 2027",
        status: "Valid",
        days: 35,
    },
    {
        number: "DXB 66201",
        model: "Audi A6 2023",
        type: "Sedan",
        subtext: "Sedan • Black",
        driver: "Olivia White",
        avatar: "https://i.pravatar.cc/80?img=24",
        insuranceExp: "08 Nov 2026",
        regExp: "12 Dec 2026",
        status: "Valid",
        days: 12,
    },
];

/* ── Global Company Documents Dataset (7 Records) ── */
export const companyDocs = [
    {
        name: "Commercial Fleet Insurance",
        subtext: "Logistics Div.",
        idNumber: "TL- 8829104",
        authority: "DED Dubai",
        issueDate: "12 Jan 2026",
        expiryDate: "Today",
        daysLeft: "0 Days Left (Today)",
        iconType: "card",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 0,
    },
    {
        name: "Office Lease Agreement",
        subtext: "Floor 42, Marina Tower",
        idNumber: "TL- 8829105",
        authority: "ABU Dhabi",
        issueDate: "15 Jan 2026",
        expiryDate: "Yesterday",
        daysLeft: "1 Day Overdue",
        iconType: "building",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: -1,
    },
    {
        name: "Chamber of Commerce Cert",
        subtext: "Corporate",
        idNumber: "TL- 8829106",
        authority: "Sharjah",
        issueDate: "18 Jan 2026",
        expiryDate: "17 Jan 2026",
        daysLeft: "2 Days Left",
        iconType: "shield",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 2,
    },
    {
        name: "Main Trade License",
        subtext: "Dubai HQ",
        idNumber: "TL- 8829104",
        authority: "DED Dubai",
        issueDate: "12 Jan 2026",
        expiryDate: "11 Jan 2026",
        daysLeft: "5 Days Left",
        iconType: "grid",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 5,
    },
    {
        name: "Industrial Operation Permit",
        subtext: "Jebel Ali Plant",
        idNumber: "TL- 9901233",
        authority: "JAFZA",
        issueDate: "01 Feb 2026",
        expiryDate: "31 Jan 2026",
        daysLeft: "12 Days Left",
        iconType: "grid",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 12,
    },
    {
        name: "Environmental Compliance Cert",
        subtext: "Operations",
        idNumber: "TL- 4455112",
        authority: "Dubai Municipality",
        issueDate: "10 Feb 2026",
        expiryDate: "09 Feb 2026",
        daysLeft: "25 Days Left",
        iconType: "shield",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 25,
    },
    {
        name: "Civil Defence Safety Permit",
        subtext: "Dubai HQ",
        idNumber: "TL- 7788990",
        authority: "Dubai Civil Defence",
        issueDate: "05 Mar 2026",
        expiryDate: "04 Mar 2026",
        daysLeft: "45 Days Left",
        iconType: "building",
        iconBg: "bg-[#E5E9F8] text-[#5949BE]",
        days: 45,
    },
];

/* ── Global Action Items Dataset ── */
export const actionItems = [
    {
        name: "Elena Rodriguez",
        subtext: "Birthday",
        category: "Birthday",
        categoryBg: "bg-violet-100 text-violet-600",
        date: "Today",
        status: "🎂 Today",
        statusColor: "text-violet-600 font-semibold",
        initials: "ER",
        days: 0,
    },
    {
        name: "Alex Vance",
        subtext: "Work Anniversary",
        category: "Special Event",
        categoryBg: "bg-rose-100 text-rose-600",
        date: "Yesterday",
        status: "• Yesterday",
        statusColor: "text-rose-500",
        initials: "AV",
        days: -1,
    },
    {
        name: "John Doe",
        subtext: "Work Anniversary (5 Yrs)",
        category: "Special Event",
        categoryBg: "bg-rose-100 text-rose-600",
        date: "Oct 15, 2026",
        status: "• 3 Days",
        statusColor: "text-rose-500",
        initials: "JD",
        days: 3,
    },
    {
        name: "Michael Chen",
        subtext: "Work Anniversary (5 Yrs)",
        category: "Special Event",
        categoryBg: "bg-rose-100 text-rose-600",
        date: "Oct 18, 2026",
        status: "6 Days",
        statusColor: "text-gray-500",
        initials: "MC",
        days: 6,
    },
    {
        name: "Sarah Jenkins",
        subtext: "Birthday",
        category: "Birthday",
        categoryBg: "bg-violet-100 text-violet-600",
        date: "Oct 22, 2026",
        status: "10 Days",
        statusColor: "text-gray-500",
        initials: "SJ",
        days: 10,
    },
];

/* ── Dashboard Overview Data ── */
export const dashboardData = {
    overviewStats: [
        { title: "Total Revenue", value: "Đ 284,500", change: "+14.2%", isPositive: true, subtext: "vs last month", bg: "bg-violet-50", accent: "text-violet-600" },
        { title: "Total Sales", value: "Đ 192,350", change: "+8.5%", isPositive: true, subtext: "1,420 orders", bg: "bg-indigo-50", accent: "text-indigo-600" },
        { title: "Total Purchases", value: "Đ 98,120", change: "-3.1%", isPositive: false, subtext: "48 vendor invoices", bg: "bg-purple-50", accent: "text-purple-600" },
        { title: "Net Profit", value: "Đ 94,230", change: "+18.7%", isPositive: true, subtext: "33.1% profit margin", bg: "bg-emerald-50", accent: "text-emerald-600" }
    ],
    monthlyRevenueVsExpense: [
        { label: "Jan", revenue: 42000, expense: 28000, profit: 14000 },
        { label: "Feb", revenue: 48000, expense: 31000, profit: 17000 },
        { label: "Mar", revenue: 55000, expense: 33000, profit: 22000 },
        { label: "Apr", revenue: 52000, expense: 29000, profit: 23000 },
        { label: "May", revenue: 61000, expense: 35000, profit: 26000 },
        { label: "Jun", revenue: 68000, expense: 38000, profit: 30000 },
        { label: "Jul", revenue: 74000, expense: 41000, profit: 33000 },
    ],
    counterDistribution: [
        { label: "Counter 1", value: 35, color: "#6F57DE" },
        { label: "Counter 2", value: 25, color: "#8B5CF6" },
        { label: "Counter 3", value: 20, color: "#A78BFA" },
        { label: "Counter 4", value: 12, color: "#C4B5FD" },
        { label: "Counter 5", value: 8, color: "#DDD6FE" },
    ],
    recentTransactions: [
        { id: "INV-9021", customer: "Al Maktoum Ltd", amount: "Đ 12,450", date: "Just now", status: "Completed", type: "Sales" },
        { id: "INV-9020", customer: "Emirates Trading", amount: "Đ 8,900", date: "15 min ago", status: "Completed", type: "Sales" },
        { id: "PO-4412", supplier: "Global Supplies FZE", amount: "Đ 15,200", date: "1 hour ago", status: "Pending", type: "Purchase" },
        { id: "INV-9019", customer: "Gulf Retail LLC", amount: "Đ 4,350", date: "2 hours ago", status: "Completed", type: "Sales" },
        { id: "TAX-2025-01", supplier: "FTA Dubai", amount: "Đ 6,120", date: "Yesterday", status: "Filed", type: "Tax" },
    ]
};

/* ── Sales Analysis Data ── */
export const salesData = {
    summary: [
        { label: "Gross Sales", value: "Đ 428,900", change: "+12.4%", period: "This Month" },
        { label: "Avg Transaction", value: "Đ 340.50", change: "+4.1%", period: "Per Invoice" },
        { label: "Total Orders", value: "1,260", change: "+9.2%", period: "Completed" },
        { label: "Returns & Refund", value: "Đ 3,450", change: "-1.8%", period: "0.8% of sales" }
    ],
    monthlyTrend: [
        { label: "Week 1", retail: 28000, wholesale: 19000, online: 12000 },
        { label: "Week 2", retail: 34000, wholesale: 24000, online: 15000 },
        { label: "Week 3", retail: 31000, wholesale: 22000, online: 14000 },
        { label: "Week 4", retail: 42000, wholesale: 29000, online: 18000 },
    ],
    categoryBreakdown: [
        { label: "Electronics & POS", value: 40, amount: "Đ 171,560", color: "#6F57DE" },
        { label: "Office Equipment", value: 25, amount: "Đ 107,225", color: "#3B82F6" },
        { label: "Consumables", value: 20, amount: "Đ 85,780", color: "#10B981" },
        { label: "Services & Support", value: 15, amount: "Đ 64,335", color: "#F59E0B" }
    ],
    topProducts: [
        { rank: "#1", name: "Touch POS Terminal Pro 15\"", category: "Hardware", code: "POS-1001", qty: 240, revenue: "Đ 96,000", growth: "+22%" },
        { rank: "#2", name: "Thermal Receipt Printer 80mm", category: "Hardware", code: "PRN-204", qty: 380, revenue: "Đ 76,000", growth: "+15%" },
        { rank: "#3", name: "Barcode Scanner 2D Wireless", category: "Accessories", code: "SCN-305", qty: 410, revenue: "Đ 61,500", growth: "+18%" },
        { rank: "#4", name: "Automatic Cash Drawer HD", category: "Hardware", code: "CDR-102", qty: 190, revenue: "Đ 47,500", growth: "+8%" },
        { rank: "#5", name: "Paper Roll 80x80 (Box of 50)", category: "Consumables", code: "CON-009", qty: 650, revenue: "Đ 32,500", growth: "+30%" }
    ]
};

/* ── Purchase Analysis Data ── */
export const purchaseData = {
    summary: [
        { label: "Total Purchases", value: "Đ 215,800", change: "-4.2%", period: "This Month" },
        { label: "Active Suppliers", value: "34 Vendors", change: "+2 new", period: "Approved list" },
        { label: "Open PO Count", value: "12 Orders", change: "Đ 45,200", period: "In transit" },
        { label: "Avg Payment Term", value: "30 Days", change: "98% on time", period: "Credit period" }
    ],
    monthlyPurchaseTrend: [
        { label: "Jan", hardware: 45000, accessories: 15000, consumables: 8000 },
        { label: "Feb", hardware: 52000, accessories: 18000, consumables: 9500 },
        { label: "Mar", hardware: 48000, accessories: 16500, consumables: 11000 },
        { label: "Apr", hardware: 61000, accessories: 21000, consumables: 12500 },
        { label: "May", hardware: 58000, accessories: 19000, consumables: 10500 },
        { label: "Jun", hardware: 66000, accessories: 23000, consumables: 13000 },
    ],
    vendorDistribution: [
        { label: "TechData Middle East", value: 38, amount: "Đ 82,000", color: "#6F57DE" },
        { label: "Epson Gulf FZE", value: 27, amount: "Đ 58,260", color: "#3B82F6" },
        { label: "Honeywell Logistics", value: 20, amount: "Đ 43,160", color: "#10B981" },
        { label: "Others", value: 15, amount: "Đ 32,380", color: "#F59E0B" }
    ],
    purchaseOrders: [
        { id: "PO-8812", vendor: "TechData Middle East", date: "14 Jan 2026", items: "120 Units POS Terminal", amount: "Đ 48,000", status: "Delivered", statusBg: "bg-emerald-100 text-emerald-700" },
        { id: "PO-8813", vendor: "Epson Gulf FZE", date: "15 Jan 2026", items: "200 Printers & Ribbons", amount: "Đ 32,500", status: "In Transit", statusBg: "bg-blue-100 text-blue-700" },
        { id: "PO-8814", vendor: "Honeywell Logistics", date: "16 Jan 2026", items: "150 Wireless Scanners", amount: "Đ 22,500", status: "Pending Approval", statusBg: "bg-amber-100 text-amber-700" },
        { id: "PO-8815", vendor: "Gulf Office Supplies", date: "18 Jan 2026", items: "500 Boxes Thermal Roll", amount: "Đ 12,000", status: "Processing", statusBg: "bg-purple-100 text-purple-700" }
    ]
};

/* ── Inventory Data ── */
export const inventoryData = {
    summary: [
        { label: "Total SKUs", value: "1,450", sub: "Active items", color: "border-l-4 border-violet-500" },
        { label: "Stock Valuation", value: "Đ 842,000", sub: "At cost price", color: "border-l-4 border-blue-500" },
        { label: "Low Stock Items", value: "14 Items", sub: "Reorder required", color: "border-l-4 border-amber-500" },
        { label: "Out of Stock", value: "3 Items", sub: "Urgent PO needed", color: "border-l-4 border-rose-500" }
    ],
    categoryValuation: [
        { label: "POS Hardware", stock: 680, value: "Đ 420,000", color: "#6F57DE" },
        { label: "Printers & Scanners", stock: 450, value: "Đ 210,000", color: "#3B82F6" },
        { label: "Cash Drawers & Cables", stock: 320, value: "Đ 95,000", color: "#10B981" },
        { label: "Thermal Rolls & Supplies", stock: 1200, value: "Đ 117,000", color: "#F59E0B" }
    ],
    itemsList: [
        { sku: "SKU-1001", name: "Touch POS Terminal Pro 15\"", category: "Hardware", stock: 42, minReorder: 15, unitPrice: "Đ 1,800", status: "In Stock", statusBg: "bg-emerald-100 text-emerald-700" },
        { sku: "SKU-2004", name: "Thermal Receipt Printer 80mm", category: "Hardware", stock: 8, minReorder: 20, unitPrice: "Đ 450", status: "Low Stock", statusBg: "bg-amber-100 text-amber-700" },
        { sku: "SKU-3005", name: "Wireless Barcode Scanner", category: "Accessories", stock: 28, minReorder: 10, unitPrice: "Đ 320", status: "In Stock", statusBg: "bg-emerald-100 text-emerald-700" },
        { sku: "SKU-4001", name: "Customer Pole Display VFD", category: "Accessories", stock: 0, minReorder: 5, unitPrice: "Đ 280", status: "Out of Stock", statusBg: "bg-rose-100 text-rose-700" },
        { sku: "SKU-5009", name: "Paper Roll 80x80 Box", category: "Consumables", stock: 140, minReorder: 50, unitPrice: "Đ 95", status: "In Stock", statusBg: "bg-emerald-100 text-emerald-700" }
    ]
};

/* ── Tax Report Data ── */
export const taxData = {
    summary: [
        { label: "Output VAT (Sales)", value: "Đ 21,445.00", sub: "5% VAT collected" },
        { label: "Input VAT (Purchases)", value: "Đ 10,790.00", sub: "5% VAT paid" },
        { label: "Net VAT Payable", value: "Đ 10,655.00", sub: "Due by 28th Feb" },
        { label: "Compliance Status", value: "100% On-Time", sub: "FTA Registered" }
    ],
    monthlyVatTrend: [
        { label: "Q1 2025", salesVat: 18500, purchaseVat: 9200, netPayable: 9300 },
        { label: "Q2 2025", salesVat: 20200, purchaseVat: 10100, netPayable: 10100 },
        { label: "Q3 2025", salesVat: 22100, purchaseVat: 11400, netPayable: 10700 },
        { label: "Q4 2025", salesVat: 24500, purchaseVat: 12100, netPayable: 12400 },
    ],
    filingsLog: [
        { period: "Q4 2025 (Oct - Dec)", trn: "100293848100003", vatAmount: "Đ 12,400.00", filingDate: "28 Jan 2026", status: "Filed & Paid", statusBg: "bg-emerald-100 text-emerald-700" },
        { period: "Q3 2025 (Jul - Sep)", trn: "100293848100003", vatAmount: "Đ 10,700.00", filingDate: "27 Oct 2025", status: "Filed & Paid", statusBg: "bg-emerald-100 text-emerald-700" },
        { period: "Q2 2025 (Apr - Jun)", trn: "100293848100003", vatAmount: "Đ 10,100.00", filingDate: "28 Jul 2025", status: "Filed & Paid", statusBg: "bg-emerald-100 text-emerald-700" },
        { period: "Q1 2025 (Jan - Mar)", trn: "100293848100003", vatAmount: "Đ 9,300.00", filingDate: "26 Apr 2025", status: "Filed & Paid", statusBg: "bg-emerald-100 text-emerald-700" },
    ]
};

/* ── Account Report Data ── */
export const accountData = {
    summary: [
        { label: "Total Assets", value: "Đ 1,845,000", sub: "Cash & Inventory" },
        { label: "Total Liabilities", value: "Đ 320,000", sub: "Accounts Payable" },
        { label: "Net Equity", value: "Đ 1,525,000", sub: "Retained Earnings" },
        { label: "Cash on Hand", value: "Đ 412,500", sub: "Dubai Islamic Bank" }
    ],
    monthlyProfitLoss: [
        { label: "Aug", grossRevenue: 85000, operatingExpenses: 42000, netIncome: 43000 },
        { label: "Sep", grossRevenue: 92000, operatingExpenses: 44000, netIncome: 48000 },
        { label: "Oct", grossRevenue: 98000, operatingExpenses: 46000, netIncome: 52000 },
        { label: "Nov", grossRevenue: 105000, operatingExpenses: 49000, netIncome: 56000 },
        { label: "Dec", grossRevenue: 120000, operatingExpenses: 55000, netIncome: 65000 },
        { label: "Jan", grossRevenue: 114000, operatingExpenses: 51000, netIncome: 63000 },
    ],
    ledgerEntries: [
        { ref: "JRN-401", date: "15 Jan 2026", account: "Sales Revenue", debit: "-", credit: "Đ 18,240", description: "Daily POS Counter 1 Sales" },
        { ref: "JRN-402", date: "15 Jan 2026", account: "Accounts Payable", debit: "Đ 15,200", credit: "-", description: "Vendor Payment - TechData" },
        { ref: "JRN-403", date: "14 Jan 2026", account: "Office Rent Expense", debit: "Đ 12,000", credit: "-", description: "Monthly HQ Rent Payment" },
        { ref: "JRN-404", date: "12 Jan 2026", account: "Salaries Expense", debit: "Đ 65,000", credit: "-", description: "January Staff Payroll" },
    ]
};

/* ── Notifications Data ── */
export const notificationsData = [
    { id: 1, title: "Visa Expiry Alert", message: "Sundar Pichai's visa expires in 5 days (12 Oct 2026).", time: "10 mins ago", category: "Expiry", isUnread: true, bg: "bg-rose-50 border-rose-200" },
    { id: 2, title: "Trade License Expiry", message: "Dubai HQ Main Trade License expires in 12 days.", time: "1 hour ago", category: "Doc Expiry", isUnread: true, bg: "bg-amber-50 border-amber-200" },
    { id: 3, title: "Low Stock Warning", message: "Thermal Receipt Printer stock reached minimum threshold (8 left).", time: "3 hours ago", category: "Inventory", isUnread: false, bg: "bg-blue-50 border-blue-200" },
    { id: 4, title: "POS Counter 1 Peak Sales", message: "Counter 1 crossed Đ 18,000 in sales today.", time: "Yesterday", category: "Sales", isUnread: false, bg: "bg-violet-50 border-violet-200" },
    { id: 5, title: "VAT Return Remind", message: "Q4 2025 VAT filing successfully confirmed by FTA.", time: "2 days ago", category: "Tax", isUnread: false, bg: "bg-emerald-50 border-emerald-200" }
];

/* ── Settings Data ── */
export const settingsData = {
    profile: {
        name: "Angel Delulu",
        email: "angel.delulu@forza.com",
        role: "Super Admin",
        phone: "+971 50 998 8776",
        avatar: "https://i.pravatar.cc/80?img=47"
    },
    company: {
        name: "FORZA Retail & POS Solutions LLC",
        trn: "100293848100003",
        currency: "Đ",
        address: "Marina Tower, Floor 42, Dubai, UAE"
    }
};

/* ── Help & FAQs Data ── */
export const helpData = [
    {
        category: "Counter & POS Reports",
        faqs: [
            { q: "How do I filter sales by individual counter?", a: "Navigate to Counter Report page and click on the counter tabs at the top (C1, C2, C3, etc.)." },
            { q: "Can I export POS summaries to Excel?", a: "Yes, click on the Export button at the top-right of the POS Report table to download CSV/Excel files." }
        ]
    },
    {
        category: "Document Expiry Tracking",
        faqs: [
            { q: "How are document expiration alerts triggered?", a: "Alerts are automatically calculated based on remaining days. Items under 30 days are highlighted in red/amber." },
            { q: "Can I add custom document types for employees?", a: "Yes, open the Employee detail side panel and click 'Add Document'." }
        ]
    },
    {
        category: "Tax & VAT Compliance",
        faqs: [
            { q: "Is the 5% UAE VAT rate automatically calculated?", a: "Yes, all sales and purchase invoices automatically calculate 5% VAT according to FTA guidelines." }
        ]
    }
];

